######################################################################
# Automatically generated by qmake (2.01a) mer. avr. 1 13:16:04 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test.cpp
